apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: flask-app
  template:
    metadata:
      labels:
        run: flask-app
    spec:
      containers:
      - name: flask-app
        image: aymanazzam07/flask-app:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_USERNAME
          value: root
        - name: DB_NAME
          value: courses_app

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    run: flask-app
spec:
  selector:
    run: flask-app
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer